# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNac', models.DateField()),
                ('foto', models.CharField(max_length=300)),
                ('tlf', models.CharField(max_length=11)),
            ],
        ),
    ]
