# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=1000)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='Registro.orden')),
            ],
        ),
    ]
