# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNac',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tlf',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
