# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso',
            old_name='ingrediente',
            new_name='ingredientes',
        ),
    ]
