# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Registro.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='billetera',
            fields=[
                ('idBilletera', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Registro.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='contiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('idIngr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('idItem', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
                ('precio', models.PositiveIntegerField()),
                ('foto', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('idMenu', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contieneRel', models.ManyToManyField(through='Registro.contiene', to='Registro.item')),
            ],
        ),
        migrations.CreateModel(
            name='ofrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveIntegerField()),
                ('idRest', models.PositiveIntegerField()),
                ('idIngr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('nroOrden', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParam', models.PositiveIntegerField()),
                ('horarioCierre', models.TimeField()),
                ('horarioEntrada', models.TimeField()),
                ('cantPuestos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRest', models.PositiveIntegerField()),
                ('idIngr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.ingrediente')),
                ('usernameA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='posee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIngr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.ingrediente')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.item')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Registro.usuario')),
                ('nombreEmpr', models.CharField(max_length=20)),
                ('rif', models.CharField(max_length=10)),
                ('ofreceRel', models.ManyToManyField(through='Registro.ofrece', to='Registro.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.orden')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.item')),
                ('nroOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.orden')),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('idTrans', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usernameP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.proveedor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='realizaRel',
            field=models.ManyToManyField(through='Registro.realiza', to='Registro.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='tieneRel',
            field=models.ManyToManyField(through='Registro.tiene', to='Registro.item'),
        ),
        migrations.AddField(
            model_name='ofrece',
            name='usernameP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.proveedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='poseeRel',
            field=models.ManyToManyField(through='Registro.posee', to='Registro.ingrediente'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='consultaRel',
            field=models.ManyToManyField(through='Registro.consulta', to='Registro.proveedor'),
        ),
        migrations.AddField(
            model_name='contiene',
            name='idItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.item'),
        ),
        migrations.AddField(
            model_name='contiene',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.menu'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idIngr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.ingrediente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.menu'),
        ),
        migrations.AddField(
            model_name='billetera',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.cliente'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='idParam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.parametro'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usernameP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='tiene',
            unique_together=set([('nroOrden', 'idItem')]),
        ),
        migrations.AlterUniqueTogether(
            name='realiza',
            unique_together=set([('username', 'nroOrden')]),
        ),
        migrations.AlterUniqueTogether(
            name='posee',
            unique_together=set([('idItem', 'idIngr')]),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set([('usernameP', 'usernameA', 'idIngr')]),
        ),
        migrations.AlterUniqueTogether(
            name='ofrece',
            unique_together=set([('usernameP', 'idIngr')]),
        ),
        migrations.AlterUniqueTogether(
            name='contiene',
            unique_together=set([('idMenu', 'idItem')]),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set([('username', 'idIngr')]),
        ),
    ]
