# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20160701_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='cantidad',
        ),
    ]
