# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registro', '0002_auto_20160609_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieneRel', models.ManyToManyField(to='Registro.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordenActual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='realizaRel',
        ),
        migrations.AddField(
            model_name='orden',
            name='totalPagado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='orden',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tlf',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombreEmpr',
            field=models.CharField(max_length=40),
        ),
    ]
