# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
