# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20160522_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tlf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
