# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registro', '0002_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='egreso',
            fields=[
                ('idTrans', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=3, max_digits=30)),
                ('fecha', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
