# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_remove_egreso_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
