# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_auto_20160630_2141'),
        ('Registro', '0003_egreso'),
    ]

    operations = [
    ]
