# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_auto_20160525_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='idBilletera',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='idIngr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='idItem',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='idMenu',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nroOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='idTrans',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
